name: MacOS
on:
  workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        qt_ver: [5.15.2]
        qt_arch: [clang_64]
        msvc_arch: [x64]
    # 步骤
    steps:
      # 安装Python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.5.4'
          architecture: '${{ matrix.msvc_arch }}'
      # 安装Qt
      - name: Install Qt5
        if: startsWith(matrix.qt_ver, '5')
        # 使用外部action。这个action专门用来安装Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          set-env: 'true'
          aqtversion: '>=2.1.0'
          py7zrversion: '>=0.18.9'
      # 拉取代码
      - uses: actions/checkout@v3
        with:
          ref: '5.15.2'
          fetch-depth: 3
          submodules: true
      # 编译
      - name: Build Qt
        id: build
        run: |
          export PATH=/opt/hostedtoolcache/Python/3.5.4/${{ matrix.msvc_arch }}/bin:$PATH
          export pythonLocation=/opt/hostedtoolcache/Python/3.5.4/${{ matrix.msvc_arch }}/bin
          echo $PATH
          python3 -m pip install -U py7zr
          python3 build.py -p Windows -a ${{ matrix.msvc_arch }} -b sip
          python3 build.py -p Windows -a ${{ matrix.msvc_arch }} -b PyQt5
          python3 mkdist.py -p Windows -a ${{ matrix.msvc_arch }} -v 5.15.2
          python3 test.py -p Windows -a ${{ matrix.msvc_arch }} -v 5.15.2
      # 下载
      - uses: actions/upload-artifact@v3
        with:
          name: PyQtWebKit_macos_${{ matrix.qt_ver }}_${{ matrix.qt_arch }}
          path: dist/**/*.whl
